"""
Convert a 1-bit PNG into a C header for the V2 e-paper (128x296), or with
--oled for the rear OLED (128x64, both boards).

Usage:
    python helpers/eink_image.py assets/eink/splash.png
    python helpers/eink_image.py assets/eink/splash.png src/Display/EInk/Images/Splash.h
    python helpers/eink_image.py --oled assets/eink/bajgiel-oled.png src/Display/Images/BajgielOled.h

The generated header is committed, so a build never needs Python or Pillow. The
PNG itself stays out of git (see .gitignore) - keep your artwork wherever you
like and rerun this script after changing it.

Contract for the PNG (nothing here is lenient - art is authored, not massaged):
  * exactly 128x296, portrait, drawn upright as it is seen on the device
    (--oled: exactly 128x64, landscape, as seen on the OLED)
  * pure black and white only: black is ink, white is paper
    (--oled: white is a lit pixel, black is off - authored as it looks)
  * already dithered by the author; this script never thresholds or dithers
  * no alpha channel - flatten it first

Output matches Adafruit_GFX drawBitmap(): row-major, MSB first, a set bit is
black (--oled: white). 128 px is exactly 16 bytes, so one line of the array is one image row.
The same PNG always produces byte-identical output.
"""

import os
import sys

from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, '..')
IMAGES_DIR = os.path.join(ROOT, 'src', 'Display', 'EInk', 'Images')
OLED_IMAGES_DIR = os.path.join(ROOT, 'src', 'Display', 'Images')

WIDTH = 128
BYTES_PER_ROW = WIDTH // 8

# Target -> (height, the PNG value that sets a bit, what a set bit means).
TARGETS = {
    'eink': (296, 0, 'INK'),
    'oled': (64, 255, 'LIT'),
}


def fail(message):
    print('error: %s' % message)
    sys.exit(1)


def load_pixels(path, height):
    if not os.path.isfile(path):
        fail('no such file: %s' % path)

    image = Image.open(path)

    if image.mode in ('RGBA', 'LA') or 'transparency' in image.info:
        fail('%s has an alpha channel; flatten it onto white first' % path)

    if image.size != (WIDTH, height):
        fail('%s is %dx%d, expected %dx%d'
             % (path, image.size[0], image.size[1], WIDTH, height))

    pixels = list(image.convert('L').getdata())

    extra = sorted(set(pixels) - {0, 255})
    if extra:
        fail('%s is not pure black and white - found %d other grey level(s), e.g. %s. '
             'Dither or threshold it in your editor before converting.'
             % (path, len(extra), extra[:5]))

    return pixels


def pack(pixels, height, set_value):
    """Row-major, MSB first, a bit is set where the pixel equals set_value."""
    data = bytearray()

    for y in range(height):
        row = pixels[y * WIDTH:(y + 1) * WIDTH]
        for byteIndex in range(BYTES_PER_ROW):
            byte = 0
            for bit in range(8):
                if row[byteIndex * 8 + bit] == set_value:
                    byte |= 0x80 >> bit
            data.append(byte)

    return data


def render(data, name, source, height, meaning):
    guard = '%s_IMAGE_H' % name
    lines = [
        '#ifndef %s' % guard,
        '#define %s' % guard,
        '',
        '// Generated by helpers/eink_image.py from %s - do not edit by hand.' % source,
        '// Adafruit_GFX drawBitmap format: row-major, MSB first, a set bit is %s.' % meaning,
        '',
        '#include <Arduino.h>',
        '',
        'constexpr int16_t %s_WIDTH = %d;' % (name, WIDTH),
        'constexpr int16_t %s_HEIGHT = %d;' % (name, height),
        '',
        '// One line per image row (%d px = %d bytes).' % (WIDTH, BYTES_PER_ROW),
        'const uint8_t %s_BITMAP[] PROGMEM = {' % name,
    ]

    for offset in range(0, len(data), BYTES_PER_ROW):
        row = data[offset:offset + BYTES_PER_ROW]
        lines.append('    ' + ' '.join('0x%02X,' % b for b in row))

    lines += [
        '};',
        '',
        '#endif //%s' % guard,
        '',
    ]

    return '\n'.join(lines)


def main():
    args = sys.argv[1:]
    mode = 'eink'
    if args and args[0] == '--oled':
        mode = 'oled'
        args = args[1:]

    if not args:
        print(__doc__.strip())
        sys.exit(1)

    height, set_value, meaning = TARGETS[mode]
    source = args[0]
    stem = os.path.splitext(os.path.basename(source))[0]
    images_dir = OLED_IMAGES_DIR if mode == 'oled' else IMAGES_DIR
    target = args[1] if len(args) > 1 else os.path.join(images_dir, '%s.h' % stem.capitalize())

    # The identifiers follow the header, not the PNG: Splash.h always defines
    # SPLASH_BITMAP, whichever artwork file it was generated from.
    name = os.path.splitext(os.path.basename(target))[0].upper()

    if not name.isidentifier():
        fail('%s does not make a valid C identifier' % name)

    pixels = load_pixels(source, height)
    data = pack(pixels, height, set_value)
    if len(data) != BYTES_PER_ROW * height:
        fail('packed %d bytes, expected %d' % (len(data), BYTES_PER_ROW * height))

    os.makedirs(os.path.dirname(os.path.abspath(target)), exist_ok=True)
    with open(target, 'w', encoding='utf-8', newline='\n') as handle:
        handle.write(render(data, name, source.replace('\\', '/'), height, meaning))

    marked = sum(1 for p in pixels if p == set_value)
    print('%s -> %s' % (source, target))
    print('%d bytes, %d px %s (%.1f%%)' % (len(data), marked, meaning.lower(), 100.0 * marked / (WIDTH * height)))


if __name__ == '__main__':
    main()
