#!/usr/bin/env python3
"""
Generate an Adafruit-GFX font header from a TTF, for the e-paper's big score.

Why this exists: Adafruit's largest bundled font is 24 pt, and the match screen
needs ~80 px digits. setTextSize(3) gets there by replicating each pixel 3x3,
which is what put visible stair-steps ("teeth") on the numbers. Rendering the
glyphs at their real pixel size instead gives smooth edges - as smooth as a 1-bit
panel can be; there is no grey available, so this is monochrome FreeType output,
not antialiasing.

Digits only, by design: nothing else is ever shown this large, and a full ASCII
range at this size would be ~25 KB of PROGMEM.

    python helpers/eink_font.py                 # regenerate with the defaults
    python helpers/eink_font.py --list-heights  # cap height vs max digit width

The generated header is committed, so a build needs neither Python nor Pillow.
"""

import argparse
import os

from PIL import Image, ImageDraw, ImageFont

DIGITS = "0123456789"
DEFAULT_FONT = "C:/Windows/Fonts/arialbd.ttf"
DEFAULT_OUT = "src/Display/EInk/Fonts/ScoreDigits.h"
DEFAULT_NAME = "ScoreDigits"

# The panel is 128 px wide. Two digits plus a margin either side must fit, so the
# font size is chosen by width, not by height - see pick_size().
PANEL_WIDTH = 128
SIDE_MARGIN = 4


def render(font, ch, pad=40):
    """The glyph's tight bitmap plus its offsets from the pen position."""
    ascent, descent = font.getmetrics()
    img = Image.new("1", (pad * 3, ascent + descent + pad * 2), 0)
    draw = ImageDraw.Draw(img)
    # anchor "ls" = left edge, baseline; so the pen sits exactly at (pad, baseline).
    baseline = pad + ascent
    draw.text((pad, baseline), ch, font=font, fill=1, anchor="ls")

    box = img.getbbox()
    if box is None:
        return None, 0, 0, 0, 0

    left, top, right, bottom = box
    return img.crop(box), right - left, bottom - top, left - pad, top - baseline


def digit_metrics(font):
    """(cap height, widest advance) for the digit set."""
    heights, advances = [], []
    for ch in DIGITS:
        _, _, h, _, _ = render(font, ch)
        heights.append(h)
        advances.append(int(round(font.getlength(ch))))
    return max(heights), max(advances)


def pick_size(path, budget):
    """Largest ppem whose two widest digits still fit inside `budget` pixels."""
    best = None
    for size in range(10, 400):
        font = ImageFont.truetype(path, size)
        _, advance = digit_metrics(font)
        if advance * 2 > budget:
            break
        best = (size, font)
    if best is None:
        raise SystemExit("no usable size for %s" % path)
    return best


def pack(bitmap):
    """1 bpp, row-major, MSB first, padded to a byte at the end of each glyph -
    which is what Adafruit_GFX::drawChar() assumes (it resets its bit counter per
    glyph and indexes bitmapOffset as a byte)."""
    out, byte, bits = [], 0, 0
    for y in range(bitmap.height):
        for x in range(bitmap.width):
            byte = (byte << 1) | (1 if bitmap.getpixel((x, y)) else 0)
            bits += 1
            if bits == 8:
                out.append(byte)
                byte, bits = 0, 0
    if bits:
        out.append(byte << (8 - bits))
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--font", default=DEFAULT_FONT)
    ap.add_argument("--out", default=DEFAULT_OUT)
    ap.add_argument("--name", default=DEFAULT_NAME)
    ap.add_argument("--budget", type=int, default=PANEL_WIDTH - 2 * SIDE_MARGIN)
    ap.add_argument("--list-heights", action="store_true")
    args = ap.parse_args()

    size, font = pick_size(args.font, args.budget)
    cap, advance = digit_metrics(font)

    if args.list_heights:
        print("%s at %d ppem: cap height %d px, widest digit advance %d px "
              "(two digits %d of %d)" % (os.path.basename(args.font), size, cap,
                                         advance, advance * 2, args.budget))
        return

    ascent, descent = font.getmetrics()
    bitmaps, glyphs = [], []
    for ch in DIGITS:
        bmp, w, h, xo, yo = render(font, ch)
        glyphs.append((len(bitmaps), w, h, int(round(font.getlength(ch))), xo, yo))
        bitmaps.extend(pack(bmp))

    guard = "EINK_FONT_%s_H" % args.name.upper()
    lines = [
        "#ifndef %s" % guard,
        "#define %s" % guard,
        "",
        "// GENERATED by helpers/eink_font.py - do not edit by hand.",
        "// Source: %s at %d ppem. Digits 0-9 only; cap height %d px, widest"
        % (os.path.basename(args.font), size, cap),
        "// digit %d px, so two of them fit the 128 px panel with a margin." % advance,
        "//",
        "// Rendered at its real size rather than scaled up from a 24 pt font with",
        "// setTextSize(), which is what made the score look stair-stepped.",
        "",
        "#include <Adafruit_GFX.h>",
        "",
        "const uint8_t %sBitmaps[] PROGMEM = {" % args.name,
    ]
    for i in range(0, len(bitmaps), 12):
        lines.append("    " + " ".join("0x%02X," % b for b in bitmaps[i:i + 12]))
    lines += [
        "};",
        "",
        "const GFXglyph %sGlyphs[] PROGMEM = {" % args.name,
    ]
    for ch, (off, w, h, adv, xo, yo) in zip(DIGITS, glyphs):
        lines.append("    {%6d, %3d, %3d, %3d, %4d, %4d},   // '%s'"
                     % (off, w, h, adv, xo, yo, ch))
    lines += [
        "};",
        "",
        "const GFXfont %s PROGMEM = {" % args.name,
        "    (uint8_t *) %sBitmaps," % args.name,
        "    (GFXglyph *) %sGlyphs," % args.name,
        "    0x30, 0x39, %d" % (ascent + descent),
        "};",
        "",
        "#endif //%s" % guard,
        "",
    ]

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(lines))

    print("%s: %d glyphs, %d bitmap bytes, cap height %d px, widest digit %d px"
          % (args.out, len(glyphs), len(bitmaps), cap, advance))


if __name__ == "__main__":
    main()
