"""
Convert a 1-bit PNG into a C header for the V2 e-paper (128x296).

Usage:
    python helpers/eink_image.py assets/eink/splash.png
    python helpers/eink_image.py assets/eink/splash.png src/Display/EInk/Images/Splash.h

The generated header is committed, so a build never needs Python or Pillow. The
PNG itself stays out of git (see .gitignore) - keep your artwork wherever you
like and rerun this script after changing it.

Contract for the PNG (nothing here is lenient - art is authored, not massaged):
  * exactly 128x296, portrait, drawn upright as it is seen on the device
  * pure black and white only: black is ink, white is paper
  * already dithered by the author; this script never thresholds or dithers
  * no alpha channel - flatten it first

Output matches Adafruit_GFX drawBitmap(): row-major, MSB first, a set bit is
black. 128 px is exactly 16 bytes, so one line of the array is one image row.
The same PNG always produces byte-identical output.
"""

import os
import sys

from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, '..')
IMAGES_DIR = os.path.join(ROOT, 'src', 'Display', 'EInk', 'Images')

WIDTH = 128
HEIGHT = 296
BYTES_PER_ROW = WIDTH // 8


def fail(message):
    print('error: %s' % message)
    sys.exit(1)


def load_pixels(path):
    if not os.path.isfile(path):
        fail('no such file: %s' % path)

    image = Image.open(path)

    if image.mode in ('RGBA', 'LA') or 'transparency' in image.info:
        fail('%s has an alpha channel; flatten it onto white first' % path)

    if image.size != (WIDTH, HEIGHT):
        fail('%s is %dx%d, expected %dx%d'
             % (path, image.size[0], image.size[1], WIDTH, HEIGHT))

    pixels = list(image.convert('L').getdata())

    extra = sorted(set(pixels) - {0, 255})
    if extra:
        fail('%s is not pure black and white - found %d other grey level(s), e.g. %s. '
             'Dither or threshold it in your editor before converting.'
             % (path, len(extra), extra[:5]))

    return pixels


def pack(pixels):
    """Row-major, MSB first, bit set = black (ink)."""
    data = bytearray()

    for y in range(HEIGHT):
        row = pixels[y * WIDTH:(y + 1) * WIDTH]
        for byteIndex in range(BYTES_PER_ROW):
            byte = 0
            for bit in range(8):
                if row[byteIndex * 8 + bit] == 0:
                    byte |= 0x80 >> bit
            data.append(byte)

    return data


def render(data, name, source):
    guard = '%s_IMAGE_H' % name
    lines = [
        '#ifndef %s' % guard,
        '#define %s' % guard,
        '',
        '// Generated by helpers/eink_image.py from %s - do not edit by hand.' % source,
        '// Adafruit_GFX drawBitmap format: row-major, MSB first, a set bit is INK.',
        '',
        '#include <Arduino.h>',
        '',
        'constexpr int16_t %s_WIDTH = %d;' % (name, WIDTH),
        'constexpr int16_t %s_HEIGHT = %d;' % (name, HEIGHT),
        '',
        '// One line per image row (%d px = %d bytes).' % (WIDTH, BYTES_PER_ROW),
        'const uint8_t %s_BITMAP[] PROGMEM = {' % name,
    ]

    for offset in range(0, len(data), BYTES_PER_ROW):
        row = data[offset:offset + BYTES_PER_ROW]
        lines.append('    ' + ' '.join('0x%02X,' % b for b in row))

    lines += [
        '};',
        '',
        '#endif //%s' % guard,
        '',
    ]

    return '\n'.join(lines)


def main():
    if len(sys.argv) < 2:
        print(__doc__.strip())
        sys.exit(1)

    source = sys.argv[1]
    stem = os.path.splitext(os.path.basename(source))[0]
    target = sys.argv[2] if len(sys.argv) > 2 else os.path.join(IMAGES_DIR, '%s.h' % stem.capitalize())

    # The identifiers follow the header, not the PNG: Splash.h always defines
    # SPLASH_BITMAP, whichever artwork file it was generated from.
    name = os.path.splitext(os.path.basename(target))[0].upper()

    if not name.isidentifier():
        fail('%s does not make a valid C identifier' % name)

    pixels = load_pixels(source)
    data = pack(pixels)
    if len(data) != BYTES_PER_ROW * HEIGHT:
        fail('packed %d bytes, expected %d' % (len(data), BYTES_PER_ROW * HEIGHT))

    os.makedirs(os.path.dirname(os.path.abspath(target)), exist_ok=True)
    with open(target, 'w', encoding='utf-8', newline='\n') as handle:
        handle.write(render(data, name, source.replace('\\', '/')))

    black = sum(1 for p in pixels if p == 0)
    print('%s -> %s' % (source, target))
    print('%d bytes, %d px black (%.1f%%)' % (len(data), black, 100.0 * black / (WIDTH * HEIGHT)))


if __name__ == '__main__':
    main()
