# Gzips web/ into src/Web/WebAssets.generated.h (gitignored), served from flash by
# src/Web/WebAssets.cpp. Runs as a PlatformIO pre-script and standalone:
#   python helpers/web_assets.py
# The header is built whole in memory and only written when its bytes change, so
# an unchanged web/ never forces a rebuild and a failure never leaves a partial one.

import gzip
import os
import sys

# URL path, file under web/, Content-Type. The route table in PlayerSetupWebUi.cpp
# registers the same paths.
ASSETS = [
    ("/", "profile.html", "text/html; charset=utf-8"),
    ("/settings", "settings.html", "text/html; charset=utf-8"),
    ("/update", "update.html", "text/html; charset=utf-8"),
    ("/app.css", "app.css", "text/css; charset=utf-8"),
    ("/profile.js", "profile.js", "application/javascript; charset=utf-8"),
    ("/settings.js", "settings.js", "application/javascript; charset=utf-8"),
    ("/update.js", "update.js", "application/javascript; charset=utf-8"),
]

OUTPUT = os.path.join("src", "Web", "WebAssets.generated.h")


class WebAssetsError(Exception):
    pass


def _compress(name, raw):
    try:
        raw.decode("utf-8")
    except UnicodeDecodeError as e:
        raise WebAssetsError("web/%s is not valid UTF-8: %s" % (name, e))

    try:
        # mtime=0: no timestamp in the gzip header, so the output is reproducible.
        blob = gzip.compress(raw, compresslevel=9, mtime=0)
    except Exception as e:
        raise WebAssetsError("gzip failed for web/%s: %s" % (name, e))

    if gzip.decompress(blob) != raw:
        raise WebAssetsError("gzip round trip mismatch for web/%s" % name)

    return blob


def _c_bytes(blob):
    lines = []
    for i in range(0, len(blob), 16):
        lines.append("    " + ",".join("0x%02x" % b for b in blob[i:i + 16]) + ",")
    return "\n".join(lines)


def generate(project_dir):
    """Returns (header_path, written). Raises WebAssetsError on any problem."""
    web_dir = os.path.join(project_dir, "web")
    out = ["// GENERATED by helpers/web_assets.py from web/ - do not edit, not in git.",
           "#pragma once",
           "",
           "#include <stddef.h>",
           "#include <stdint.h>",
           "#include <pgmspace.h>",
           "",
           "namespace WebAssetData {",
           "struct Asset {",
           "    const char *path;",
           "    const char *contentType;",
           "    const uint8_t *data;",
           "    size_t length;",
           "};",
           ""]
    rows = []
    total_raw = total_gz = 0

    for index, (url, name, content_type) in enumerate(ASSETS):
        path = os.path.join(web_dir, name)
        if not os.path.isfile(path):
            raise WebAssetsError("missing web/%s (served at %s)" % (name, url))
        with open(path, "rb") as f:
            raw = f.read()

        blob = _compress(name, raw)
        total_raw += len(raw)
        total_gz += len(blob)
        print("web_assets: %-12s %6d B -> %5d B gz" % (name, len(raw), len(blob)))

        out.append("// web/%s" % name)
        out.append("static const uint8_t ASSET_%d[] PROGMEM = {" % index)
        out.append(_c_bytes(blob))
        out.append("};")
        out.append("")
        rows.append('    {"%s", "%s", ASSET_%d, %d},' % (url, content_type, index, len(blob)))

    out.append("static const Asset ASSETS[] = {")
    out.extend(rows)
    out.append("};")
    out.append("static const size_t COUNT = %d;" % len(ASSETS))
    out.append("}")
    out.append("")
    print("web_assets: total        %6d B -> %5d B gz" % (total_raw, total_gz))

    content = "\n".join(out).encode("ascii")
    header = os.path.join(project_dir, OUTPUT)

    if os.path.isfile(header):
        with open(header, "rb") as f:
            if f.read() == content:
                return header, False

    tmp = header + ".tmp"
    with open(tmp, "wb") as f:
        f.write(content)
    os.replace(tmp, header)
    return header, True


def _run(project_dir):
    try:
        header, written = generate(project_dir)
    except (WebAssetsError, OSError) as e:
        print("web_assets: ERROR: %s" % e, file=sys.stderr)
        return 1
    print("web_assets: %s %s" % ("wrote" if written else "unchanged", os.path.relpath(header, project_dir)))
    return 0


# SCons injects Import() into a pre-script's globals; plain python does not.
if "Import" in globals():
    Import("env")  # noqa: F821
    if _run(env["PROJECT_DIR"]) != 0:  # noqa: F821
        env.Exit(1)  # noqa: F821
else:
    sys.exit(_run(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
