# v1_bootstrap only: turns SCOREBOARD_WIFI_SSID / SCOREBOARD_WIFI_PASSWORD into
# BootstrapWifi.generated.h, which PreferencesManager.h includes under BOOTSTRAP_WIFI.
# Standalone (prints the header, writes nothing):  python helpers/wifi_bootstrap.py
#
# Why a header and not -D defines: a password with quotes, backslashes or spaces would
# have to survive PlatformIO, SCons and the Windows command line quoting; a file has one
# layer of escaping (C) and nothing else.
# Why the build dir and not src/: the header sits on the include path of this env only, so
# no other env can see it and a stale copy can never leak into v1 / v1_ota / v2.

import os
import sys

SSID_VAR = "SCOREBOARD_WIFI_SSID"
PASSWORD_VAR = "SCOREBOARD_WIFI_PASSWORD"
MAX_BYTES = 63  # PrefsData's char[64] minus the NUL


class BootstrapError(Exception):
    pass


def c_literal(text):
    r"""Quoted C string literal for the UTF-8 bytes of text. Anything outside plain
    printable ASCII, plus \ " and ? (trigraphs), becomes a 3-digit octal escape, so
    a following digit can never extend it."""
    out = []
    for b in text.encode("utf-8"):
        if 0x20 <= b < 0x7F and chr(b) not in '\\"?':
            out.append(chr(b))
        else:
            out.append("\\%03o" % b)
    return '"' + "".join(out) + '"'


def build_header(environ):
    ssid = environ.get(SSID_VAR)
    password = environ.get(PASSWORD_VAR)
    if ssid is None or password is None:
        missing = [n for n, v in ((SSID_VAR, ssid), (PASSWORD_VAR, password)) if v is None]
        raise BootstrapError("v1_bootstrap needs %s set in the environment (empty password = open network)."
                             % " and ".join(missing))
    if not ssid:
        raise BootstrapError(SSID_VAR + " is empty.")
    if len(ssid.encode("utf-8")) > MAX_BYTES:
        raise BootstrapError("%s is over %d bytes." % (SSID_VAR, MAX_BYTES))
    if len(password.encode("utf-8")) > MAX_BYTES:
        raise BootstrapError("%s is over %d bytes." % (PASSWORD_VAR, MAX_BYTES))
    return ("// Generated by helpers/wifi_bootstrap.py - contains credentials, never commit.\n"
            "#pragma once\n"
            "#define BOOTSTRAP_WIFI_SSID %s\n"
            "#define BOOTSTRAP_WIFI_PASSWORD %s\n") % (c_literal(ssid), c_literal(password))


def write_if_changed(path, content):
    # Unchanged bytes keep the mtime, so an unchanged password never forces a rebuild.
    try:
        with open(path, encoding="utf-8", newline="") as f:
            if f.read() == content:
                return
    except OSError:
        pass
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="") as f:
        f.write(content)


def _run_in_platformio(env):
    try:
        header = build_header(os.environ)
    except BootstrapError as e:
        sys.stderr.write("\n*** wifi_bootstrap: %s\n\n" % e)
        env.Exit(1)
        return
    out_dir = os.path.join(env.subst("$BUILD_DIR"), "bootstrap")
    write_if_changed(os.path.join(out_dir, "BootstrapWifi.generated.h"), header)
    env.Append(CPPPATH=[out_dir])


try:
    Import("env")  # noqa: F821 - injected by SCons
except NameError:
    if __name__ == "__main__":
        try:
            sys.stdout.write(build_header(os.environ))
        except BootstrapError as e:
            sys.stderr.write("wifi_bootstrap: %s\n" % e)
            sys.exit(1)
else:
    _run_in_platformio(env)  # noqa: F821
