#ifndef LED_SLOT_POSITIONS_H
#define LED_SLOT_POSITIONS_H

#include <stdint.h>

#include "Board.h"

/**
 * Where every LED on the chain physically sits, in raw map units, +x right, +y
 * down (~16 units per mm). V2's origin is the e-paper centre; V1's is the colon
 * midpoint (V1 has no e-paper). Both maps share the same ~197-unit die pitch, so
 * LedSweepAnimation.h's Params::band is shared by both boards.
 *
 * Generated by helpers/led_positions.py from assets/led-map.svg (V2) and
 * assets/v1_led_map.svg (V1); `--check` verifies these tables still match the
 * maps. Do not hand-edit the rows.
 *
 * SKIP marks a slot with no front-facing die, so animations must leave it
 * untouched rather than writing black to it:
 *   V2 - the two back indicators (4, 9) and slot 2 of each digit module
 *        (12, 28, 44, 60), an unfitted chain position.
 *   V1 - the two back indicators (2, 3). V1 has no dead chain positions: every
 *        other slot is a real front die (colon, 4 digits, history bar).
 *
 * Namespace scope, not a class member: a static constexpr array member is an ODR
 * link error on GCC 8.4.
 */

#if BOARD_REV == 2

namespace LedSlots {
    enum : int16_t { SKIP = -32768 };

    constexpr int16_t POS[Board::LED_COUNT][2] = {
            {  -342,   295},  //  0  border left,  bottom outer
            {  -342,    98},  //  1  border left,  bottom inner
            {  -342,   -98},  //  2  border left,  top inner
            {  -342,  -295},  //  3  border left,  top outer
            {  SKIP,     0},  //  4  back indicator B
            {   331,   295},  //  5  border right, bottom outer
            {   331,    98},  //  6  border right, bottom inner
            {   331,   -98},  //  7  border right, top inner
            {   331,  -295},  //  8  border right, top outer
            {  SKIP,     0},  //  9  back indicator A
            {  2203,   377},  // 10  digit D
            {  2203,   180},  // 11
            {  SKIP,     0},  // 12  dead slot 2
            {  2203,  -214},  // 13
            {  2203,  -411},  // 14
            {  2020,  -606},  // 15
            {  1823,  -606},  // 16
            {  1626,  -606},  // 17
            {  1662,  -214},  // 18
            {  1662,   -17},  // 19
            {  1662,   180},  // 20
            {  1626,   573},  // 21
            {  1823,   573},  // 22
            {  2020,   573},  // 23
            {  2097,   -16},  // 24
            {  1900,   -16},  // 25
            {  1245,   377},  // 26  digit C
            {  1245,   180},  // 27
            {  SKIP,     0},  // 28  dead slot 2
            {  1245,  -214},  // 29
            {  1245,  -411},  // 30
            {  1062,  -606},  // 31
            {   865,  -606},  // 32
            {   668,  -606},  // 33
            {   705,  -214},  // 34
            {   705,   -17},  // 35
            {   705,   180},  // 36
            {   668,   573},  // 37
            {   865,   573},  // 38
            {  1062,   573},  // 39
            {  1139,   -16},  // 40
            {   942,   -16},  // 41
            {  -717,   376},  // 42  digit B
            {  -717,   179},  // 43
            {  SKIP,     0},  // 44  dead slot 2
            {  -717,  -215},  // 45
            {  -717,  -412},  // 46
            {  -900,  -607},  // 47
            { -1097,  -607},  // 48
            { -1294,  -607},  // 49
            { -1258,  -215},  // 50
            { -1258,   -18},  // 51
            { -1258,   179},  // 52
            { -1294,   572},  // 53
            { -1097,   572},  // 54
            {  -900,   572},  // 55
            {  -823,   -17},  // 56
            { -1020,   -17},  // 57
            { -1675,   376},  // 58  digit A
            { -1675,   179},  // 59
            {  SKIP,     0},  // 60  dead slot 2
            { -1675,  -215},  // 61
            { -1675,  -412},  // 62
            { -1858,  -607},  // 63
            { -2055,  -607},  // 64
            { -2252,  -607},  // 65
            { -2215,  -215},  // 66
            { -2215,   -18},  // 67
            { -2215,   179},  // 68
            { -2252,   572},  // 69
            { -2055,   572},  // 70
            { -1858,   572},  // 71
            { -1781,   -17},  // 72
            { -1978,   -17},  // 73
    };
}

#else

namespace LedSlots {
    enum : int16_t { SKIP = -32768 };

    constexpr int16_t POS[Board::LED_COUNT][2] = {
            {     0,  -197},  //  0  colon
            {     0,   197},  //  1  colon
            {  SKIP,     0},  //  2  back indicator B
            {  SKIP,     0},  //  3  back indicator A
            {   544,  -501},  //  4  digit C upper-left
            {   544,  -304},  //  5  digit C upper-left
            {   544,  -107},  //  6  digit C upper-left
            {   544,    90},  //  7  digit C lower-left
            {   544,   287},  //  8  digit C lower-left
            {   544,   484},  //  9  digit C lower-left
            {  1191,    90},  // 10  digit C lower-right
            {  1191,   287},  // 11  digit C lower-right
            {  1191,   484},  // 12  digit C lower-right
            {  1191,  -501},  // 13  digit C upper-right
            {  1191,  -304},  // 14  digit C upper-right
            {  1191,  -107},  // 15  digit C upper-right
            {  1616,  -501},  // 16  digit D upper-left
            {  1616,  -304},  // 17  digit D upper-left
            {  1616,  -107},  // 18  digit D upper-left
            {  1616,    90},  // 19  digit D lower-left
            {  1616,   287},  // 20  digit D lower-left
            {  1616,   484},  // 21  digit D lower-left
            {  2263,    90},  // 22  digit D lower-right
            {  2263,   287},  // 23  digit D lower-right
            {  2263,   484},  // 24  digit D lower-right
            {  2263,  -501},  // 25  digit D upper-right
            {  2263,  -304},  // 26  digit D upper-right
            {  2263,  -107},  // 27  digit D upper-right
            {  1746,  -621},  // 28  digit D top
            {  1943,  -621},  // 29  digit D top
            {  2140,  -621},  // 30  digit D top
            {   674,  -621},  // 31  digit C top
            {   871,  -621},  // 32  digit C top
            {  1068,  -621},  // 33  digit C top
            {   674,    -8},  // 34  digit C middle
            {   871,    -8},  // 35  digit C middle
            {  1068,    -8},  // 36  digit C middle
            {  1746,    -8},  // 37  digit D middle
            {  1943,    -8},  // 38  digit D middle
            {  2140,    -8},  // 39  digit D middle
            {  1746,   608},  // 40  digit D bottom
            {  1943,   608},  // 41  digit D bottom
            {  2140,   608},  // 42  digit D bottom
            {   674,   608},  // 43  digit C bottom
            {   871,   608},  // 44  digit C bottom
            {  1068,   608},  // 45  digit C bottom
            { -2267,  -501},  // 46  digit A upper-left
            { -2267,  -304},  // 47  digit A upper-left
            { -2267,  -107},  // 48  digit A upper-left
            { -2267,    90},  // 49  digit A lower-left
            { -2267,   287},  // 50  digit A lower-left
            { -2267,   484},  // 51  digit A lower-left
            { -1620,    90},  // 52  digit A lower-right
            { -1620,   287},  // 53  digit A lower-right
            { -1620,   484},  // 54  digit A lower-right
            { -1620,  -501},  // 55  digit A upper-right
            { -1620,  -304},  // 56  digit A upper-right
            { -1620,  -107},  // 57  digit A upper-right
            { -1195,  -501},  // 58  digit B upper-left
            { -1195,  -304},  // 59  digit B upper-left
            { -1195,  -107},  // 60  digit B upper-left
            { -1195,    90},  // 61  digit B lower-left
            { -1195,   287},  // 62  digit B lower-left
            { -1195,   484},  // 63  digit B lower-left
            {  -548,    90},  // 64  digit B lower-right
            {  -548,   287},  // 65  digit B lower-right
            {  -548,   484},  // 66  digit B lower-right
            {  -548,  -501},  // 67  digit B upper-right
            {  -548,  -304},  // 68  digit B upper-right
            {  -548,  -107},  // 69  digit B upper-right
            { -1065,  -621},  // 70  digit B top
            {  -868,  -621},  // 71  digit B top
            {  -671,  -621},  // 72  digit B top
            { -2136,  -621},  // 73  digit A top
            { -1940,  -621},  // 74  digit A top
            { -1743,  -621},  // 75  digit A top
            { -2136,    -8},  // 76  digit A middle
            { -1940,    -8},  // 77  digit A middle
            { -1743,    -8},  // 78  digit A middle
            { -1065,    -8},  // 79  digit B middle
            {  -868,    -8},  // 80  digit B middle
            {  -671,    -8},  // 81  digit B middle
            { -1065,   608},  // 82  digit B bottom
            {  -868,   608},  // 83  digit B bottom
            {  -671,   608},  // 84  digit B bottom
            { -2136,   608},  // 85  digit A bottom
            { -1940,   608},  // 86  digit A bottom
            { -1743,   608},  // 87  digit A bottom
            { -2267,  1022},  // 88  bar 0
            { -2070,  1022},  // 89  bar 1
            { -1873,  1022},  // 90  bar 2
            { -1677,  1022},  // 91  bar 3
            { -1480,  1022},  // 92  bar 4
            { -1283,  1022},  // 93  bar 5
            { -1086,  1022},  // 94  bar 6
            {  -889,  1022},  // 95  bar 7
            {  -692,  1022},  // 96  bar 8
            {  -495,  1022},  // 97  bar 9
            {  -299,  1022},  // 98  bar 10
            {  -102,  1022},  // 99  bar 11
            {    95,  1022},  // 100  bar 12
            {   292,  1022},  // 101  bar 13
            {   489,  1022},  // 102  bar 14
            {   686,  1022},  // 103  bar 15
            {   883,  1022},  // 104  bar 16
            {  1079,  1022},  // 105  bar 17
            {  1276,  1022},  // 106  bar 18
            {  1473,  1022},  // 107  bar 19
            {  1670,  1022},  // 108  bar 20
            {  1867,  1022},  // 109  bar 21
            {  2064,  1022},  // 110  bar 22
            {  2260,  1022},  // 111  bar 23
    };
}

#endif

namespace LedSlots {
    /** Which player's side of the front a slot is on. V1's colon dies sit at
     *  x == 0 and belong to neither; V2 has no slot there. */
    enum class Half : uint8_t { Left, Right, Seam };

    inline Half halfOf(const int16_t x) {
        return x < 0 ? Half::Left : (x > 0 ? Half::Right : Half::Seam);
    }
}

#endif //LED_SLOT_POSITIONS_H
